version: '2'
services:
  hkex_mongo:
    image: mongo
    ports:
      - 27017
    volumes:
      - ${COMPOSEROOT}/hkexsails/data:/data/db
    command: mongod --directoryperdb   
    env_file:
      ../.env
    
  hkexsails:
    depends_on:
      - hkex_mongo
    image: twhtanghk/hkexsails
    ports:
      - 1337
    env_file:
      - ./.env
      - ../.env
